/**
 * Renders the knowledge base into the skill as markdown.
 *
 * The app matches questions against knowledge-base.json at runtime; the skill has no server
 * to ask, so it needs the same content as prose it can answer from directly. Generating one
 * from the other is what stops the two surfaces quoting different prices.
 *
 * `--check` fails instead of writing, for CI.
 */
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "lib/core/knowledge-base.json";
const DST =
  "plugins/fo-01-front-office/skills/fo-01-multi-channel-front-office-assistant/references/knowledge-base.md";

const kb = JSON.parse(readFileSync(SRC, "utf8"));

const md = `# The knowledge base

Generated from \`${SRC}\`. Do not edit this file — edit the source and run \`npm run sync:kb\`.
The console matches questions against the same data, so both surfaces quote the same figures.

**Answer only what is here.** If a question is not covered, say so and escalate. Do not reason
your way to a plausible price, date or policy — a wrong answer given confidently costs more
than a slow one.

## Approved answers

${kb.entries
  .map(
    (e) =>
      `### ${e.id}\n\n_Asked as:_ ${e.q.map((q) => `“${q}”`).join(", ")}\n\n> ${e.a}\n`,
  )
  .join("\n")}
## Escalation triggers — these override everything above

A question matching any term below is **not** an FAQ, however much it resembles one.
"Do you offer refunds" shares almost every word with "what do you offer", which is answered
above; the trigger wins. Escalate it to the named team without attempting an answer.

${kb.triggers
  .map(
    (t) =>
      `**${t.team}** — ${t.terms.map((x) => `\`${x}\``).join(", ")}`,
  )
  .join("\n\n")}

Matched as substrings, so inflections count: "refunded" and "cancelling" both fire.
Terms are English and French; a trigger in either language routes the same way, and the reply
goes back in the language the person wrote in.
`;

if (process.argv.includes("--check")) {
  let current = null;
  try { current = readFileSync(DST, "utf8"); } catch {}
  if (current !== md) {
    console.error(`DRIFT: ${DST} is stale. Run: npm run sync:kb`);
    process.exit(1);
  }
  console.log("knowledge base in sync");
} else {
  writeFileSync(DST, md);
  console.log(`rendered ${SRC} -> ${DST}`);
}
